export const FORMATIONS = {
  "4-3-3": [
    { id: "GK", label: "GK", position: "GK", x: 50, y: 88 },
    { id: "LB", label: "LB", position: "DF", x: 15, y: 70 },
    { id: "CB1", label: "CB", position: "DF", x: 38, y: 73 },
    { id: "CB2", label: "CB", position: "DF", x: 62, y: 73 },
    { id: "RB", label: "RB", position: "DF", x: 85, y: 70 },
    { id: "LCM", label: "CM", position: "MF", x: 26, y: 48 },
    { id: "CM", label: "CDM", position: "MF", x: 50, y: 53 },
    { id: "RCM", label: "CM", position: "MF", x: 74, y: 48 },
    { id: "LW", label: "LW", position: "FW", x: 20, y: 22 },
    { id: "ST", label: "ST", position: "FW", x: 50, y: 16 },
    { id: "RW", label: "RW", position: "FW", x: 80, y: 22 },
  ],
  "4-2-3-1": [
    { id: "GK", label: "GK", position: "GK", x: 50, y: 88 },
    { id: "LB", label: "LB", position: "DF", x: 15, y: 70 },
    { id: "CB1", label: "CB", position: "DF", x: 38, y: 73 },
    { id: "CB2", label: "CB", position: "DF", x: 62, y: 73 },
    { id: "RB", label: "RB", position: "DF", x: 85, y: 70 },
    { id: "LDM", label: "DM", position: "MF", x: 35, y: 56 },
    { id: "RDM", label: "DM", position: "MF", x: 65, y: 56 },
    { id: "LAM", label: "LAM", position: "MF", x: 20, y: 36 },
    { id: "CAM", label: "CAM", position: "MF", x: 50, y: 34 },
    { id: "RAM", label: "RAM", position: "MF", x: 80, y: 36 },
    { id: "ST", label: "ST", position: "FW", x: 50, y: 16 },
  ],
  "3-5-2": [
    { id: "GK", label: "GK", position: "GK", x: 50, y: 88 },
    { id: "LCB", label: "CB", position: "DF", x: 25, y: 72 },
    { id: "CB", label: "CB", position: "DF", x: 50, y: 74 },
    { id: "RCB", label: "CB", position: "DF", x: 75, y: 72 },
    { id: "LWB", label: "LWB", position: "DF", x: 12, y: 48 },
    { id: "LCM", label: "CM", position: "MF", x: 35, y: 52 },
    { id: "CM", label: "CAM", position: "MF", x: 50, y: 46 },
    { id: "RCM", label: "CM", position: "MF", x: 65, y: 52 },
    { id: "RWB", label: "RWB", position: "DF", x: 88, y: 48 },
    { id: "LS", label: "ST", position: "FW", x: 35, y: 18 },
    { id: "RS", label: "ST", position: "FW", x: 65, y: 18 },
  ],
  "4-4-2": [
    { id: "GK", label: "GK", position: "GK", x: 50, y: 88 },
    { id: "LB", label: "LB", position: "DF", x: 15, y: 70 },
    { id: "CB1", label: "CB", position: "DF", x: 38, y: 73 },
    { id: "CB2", label: "CB", position: "DF", x: 62, y: 73 },
    { id: "RB", label: "RB", position: "DF", x: 85, y: 70 },
    { id: "LM", label: "LM", position: "MF", x: 15, y: 45 },
    { id: "LCM", label: "CM", position: "MF", x: 38, y: 48 },
    { id: "RCM", label: "CM", position: "MF", x: 62, y: 48 },
    { id: "RM", label: "RM", position: "MF", x: 85, y: 45 },
    { id: "LS", label: "ST", position: "FW", x: 35, y: 18 },
    { id: "RS", label: "ST", position: "FW", x: 65, y: 18 },
  ],
};
